# =============================================================================
# Module 19 — Architectures de référence
# Section 19.2.2 — Cluster K8s HA Debian (VRRP)
# Fichier : /etc/keepalived/keepalived.conf — nœud cp-3 (BACKUP, priority 100)
# Licence : CC BY 4.0
# =============================================================================

global_defs {
    router_id K8S_CP_3
    enable_script_security
    script_user root
}

vrrp_script check_haproxy {
    script "/usr/bin/killall -0 haproxy"
    interval 3
    weight -20
    fall 3
    rise 2
}

vrrp_instance K8S_VIP {
    state BACKUP
    interface ens192
    virtual_router_id 51
    priority 100                    # La plus basse
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass VrrPK8sX
    }

    virtual_ipaddress {
        10.2.0.100/24
    }

    track_script {
        check_haproxy
    }
}
