#
# Nom         : 05.1-rsyslog-reception-server.conf
# Module      : 3 — Administration système
# Section     : 3.5.1 — rsyslog vs journald
# Source      : module-03-administration-systeme/05.1-rsyslog-vs-journald.md
# Description : Configuration rsyslog serveur pour réception centralisée des logs.
# Testé sur   : Debian 13 (Trixie)
# Licence     : CC BY 4.0 — Formation Debian (Nicolas DEOUX)
#
# Réception TCP
module(load="imtcp")
input(type="imtcp" port="514")

# Réception UDP
module(load="imudp")
input(type="imudp" port="514")

# Stockage par machine source
template(name="RemoteHost" type="string"
    string="/var/log/remote/%HOSTNAME%/%programname%.log")

if $fromhost-ip != '127.0.0.1' then {
    action(type="omfile" dynaFile="RemoteHost")
    stop
}
