#
# Nom         : 05.1-rsyslog-mon-application.conf
# Module      : 3 — Administration système
# Section     : 3.5.1 — rsyslog vs journald
# Source      : module-03-administration-systeme/05.1-rsyslog-vs-journald.md
# Description : Configuration rsyslog pour rediriger les logs d'une application vers
#               un fichier dédié.
# Testé sur   : Debian 13 (Trixie)
# Licence     : CC BY 4.0 — Formation Debian (Nicolas DEOUX)
#
# Router les messages de local0 vers un fichier dédié
local0.*                        /var/log/mon-application.log

# Empêcher ces messages d'apparaître aussi dans syslog
local0.*                        stop
