#
# Nom         : 02.3-pam-time.conf
# Module      : 3 — Administration système
# Section     : 3.2.3 — Mots de passe et PAM
# Source      : module-03-administration-systeme/02.3-mots-de-passe-pam.md
# Description : Restrictions horaires d'accès aux comptes (PAM time).
# Testé sur   : Debian 13 (Trixie)
# Licence     : CC BY 4.0 — Formation Debian (Nicolas DEOUX)
#
# service;terminaux;utilisateurs;horaires

# Autoriser SSH pour les développeurs uniquement en semaine, 7h-21h
sshd;*;@dev;Wk0700-2100

# Interdire sudo le week-end pour les stagiaires
sudo;*;stagiaire;!Wd0000-2400
